# Configuration for CircleCI
# https://circleci.com/gh/qos-ch/logback-extensions
version: 2.0

jobs:
  build:
    branches:
      ignore: gh-pages
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "loggly/build.gradle" }}-{{ checksum  "spring/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "loggly/build.gradle" }}-{{ checksum  "spring/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check assemble --parallel
      - store_artifacts:
          path: loggly/build/reports
          destination: reports
      - store_artifacts:
          path: spring/build/reports
          destination: reports
      - store_artifacts:
          path: loggly/build/outputs
          destination: outputs
      - store_artifacts:
          path: spring/build/outputs
          destination: outputs
      - store_test_results:
          path: loggly/build/test-results
      - store_test_results:
          path: spring/build/test-results
      - run:
          name: Deploy snapshot
          command: scripts/deploysnapshot.sh
